### ISSUE TITLE
Configure the CI to run during PRs (Backend)

### ISSUE THREAD

**Issue by blackpan2** [moltimate/moltimate-backend#10]
BLOCKED BY: #9 
Size Estimation: _

Configure PRs so that they are required to pass the tests in the repo before they can be merged.

Acceptance Criteria:
- CI is configured to run project tests
- PRs are blocked for code that fails tests

**Comment by steplica** [comment]
Finished with [PR 12](https://github.com/moltimate/moltimate-backend/pull/12).
