### ISSUE TITLE
Connect to the PDB Adanced Search API

### ISSUE THREAD

**Issue by blackpan2** [moltimate/moltimate-backend#13]
Size Estimation: S

Make a search request to the PDB Advanced Search which returns a collection of results. This endpoint should be a batch endpoint and should be paginated.

Acceptance Criteria:
* Able to return a paginated request
* Function allows for input of request information (not a single hardcoded request)

Notes: 
(PDB Advanced Search)[https://www.rcsb.org/pages/webservices/rest-search#search] appears to be an endpoint that takes a block of XML in.

**Comment by steplica** [comment]
I've written some basic code that can send an Advanced Query to RCSB's PDB query API, and it returns the correct search results. Bu, we're at a point where we're not sure that we need this. We'll keep the code in our project for now, and choose to augment or remove it depending on whether we move forward with querying the PDB directly.
