### ISSUE TITLE
[SPIKE] Look into using Swagger to generate API documentation

### ISSUE THREAD

**Issue by steplica** [moltimate/moltimate-backend#31]
@blackpan2 suggested that Swagger might be a useful tool for generating thorough API documentation.

**Comment by blackpan2** [comment]
This is a link to their website [swagger.io](https://swagger.io/)

**Comment by blackpan2** [comment]
Check if Markdown is an acceptable export format (for getting it to the Wiki)

**Comment by blackpan2** [comment]
There appears to be a way to do this, but I will continue to look at the feasibility of using this extension.

Library: [swagger2markup](https://github.com/Swagger2Markup/swagger2markup)
Demo: [swagger2markup Demo](https://github.com/Swagger2Markup/spring-swagger2markup-demo)
