### ISSUE TITLE
Disable BioJava's verbose logging

### ISSUE THREAD

**Issue by steplica** [moltimate/moltimate-backend#34]
Size Estimation: S

When two active sites are aligned, BioJava floods the sever's console logs with hundreds of INFO level messages. These messages are not particularly useful, and make the server logs unusable.

Acceptance Criteria:

When two active sites are aligned, the server's console logs will not be flooded with hundreds of INFO level messages.

**Comment by jmiller656** [comment]
Tested this with the current branch. Looks like this logging only happens when you run unit tests. When the server is running we get none of the biojava logging.

This might be fine (although a little irritating for tests)

**Comment by steplica** [comment]
We should still keep this issue open because it will definitely make test debugging harder.

**Comment by blackpan2** [comment]
Moved to release 2 as part of the punch list update

**Comment by blackpan2** [comment]
@steplica Can this be closed? It would appear that this was completed alongside #67

**Comment by steplica** [comment]
This should be fixed, let's wait to confirm that unit tests run silently.
