### ISSUE TITLE
Set up spring profiles to allow for multiple deployment configurations

### ISSUE THREAD

**Issue by steplica** [moltimate/moltimate-backend#37]
Size Estimation: S

Profiles are a useful way to choose which set of application properties to apply when starting the spring boot application. Set up a default profile so that it can be used as reference to easily create additional profiles.

An example where this would be useful is having the ability to deploy with an h2 database or with a production MySQL server by choosing the right profile.

**Comment by blackpan2** [comment]
Moved to release 2 as part of the punch list update

**Comment by steplica** [comment]
Done
