### ISSUE TITLE
Verify we don't need special CORS configuration for local development

### ISSUE THREAD

**Issue by steplica** [moltimate/moltimate-backend#75]
There was a point in time where we needed a special CORS configuration so that our locally hosted frontend and backend could successfully communicate. 

Now, our frontend and backend are communicating just fine without any special CORS configuration.

We should look into whether or not this behavior is intentional. We don't want to get unexpected failures for local development down the line.

**Comment by blackpan2** [comment]
I believe at this point we've confirmed that we need a specific CORS configuration for local and for production.

@smcintosh881 Can I get confirmation on this?

@steplica I believe we can close this with the creation of the Dev and Prod CORS configs
